version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres-c
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
    volumes:
      - ecommerce-postgres:/data/postgres
    ports:
      - "5332:5432"
  docker-redis:
    image: redis:7-alpine
    container_name: docker-redis-c
    ports:
      - "6379:6379"
    volumes:
      - ecommerce-redis:/data

volumes:
  ecommerce-postgres:
  ecommerce-redis: