server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"